### ISSUE TITLE
Mod not generate name for trailer variation

### ISSUE THREAD

**Issue by AngelHeavenly** [Acc3ssViolation/ExtendedAssetEditor#10]
![image](https://user-images.githubusercontent.com/71866284/236436648-a5a3c254-cfa3-4de3-ad26-bbcb26512949.png)
![image](https://user-images.githubusercontent.com/71866284/236440401-fc22503c-b062-44b1-994b-d507118e1b27.png)
![image](https://user-images.githubusercontent.com/71866284/236440755-731fd1cd-053d-4342-89db-49710ef0c04a.png)

[output_log — копия.txt](https://github.com/Acc3ssViolation/ExtendedAssetEditor/files/11405528/output_log.txt)

[output_log.txt](https://github.com/Acc3ssViolation/ExtendedAssetEditor/files/11405537/output_log.txt)

**Comment by Acc3ssViolation** [comment]
I've tried to replicate this, but can't replicate it unfortunately.

I have pushed version 0.7.6 which adds some extra logging like this:
```
	Line 290799: Extended Asset Editor: 'Trailer Test Trailer Thing': Saved mesh variation mask as 'TrailerVariation 1'
	Line 290803: Extended Asset Editor: 'Trailer Test Trailer Thing': Saved submesh variation mask as 'TrailerVariation 2'
	Line 290807: Extended Asset Editor: 'Trailer Test Trailer Thing': Saved submesh variation mask as 'TrailerVariation 4'
	Line 290811: Extended Asset Editor: 'Trailer Test Trailer Thing': Saved submesh variation mask as 'TrailerVariation 8'
	Line 290815: Extended Asset Editor: 'Trailer Test Trailer Thing': Saved submesh variation mask as 'TrailerVariation 16'
	Line 290819: Extended Asset Editor: 'Trailer Test Trailer Thing': Saved submesh variation mask as 'TrailerVariation 32'
	Line 290823: Extended Asset Editor: 'Trailer Test Trailer Thing': Saved submesh variation mask as 'TrailerVariation 64'
	Line 290827: Extended Asset Editor: 'Trailer Test Trailer Thing': Saved submesh variation mask as 'TrailerVariation 128'
	Line 290831: Extended Asset Editor: 'Trailer Test Trailer Thing': Saved submesh variation mask as 'TrailerVariation 256'
```
Try loading, fixing and saving the trailer asset and check the logs to see if it says anything about it.

Note that the mod first creates a copy of the assets before saving them. The mesh name changes are done on the copy and are not visible using mod tools on the main asset. You'd have to fully reload the editor and load the asset to actually see the names being applied.

It is also possible another mod is causing issues, perhaps one of the loading mods. If nothing else works try disabling those before using the editor.

**Comment by AngelHeavenly** [comment]
```
2,034,345ms | Extended Asset Editor: Generating thumbnails for 'TrailerVL80-tempfix23' (TrailerVL80-tempfix23 (UnityEngine.GameObject))
2,034,433ms | Extended Asset Editor: 'TrailerVL80-tempfix23': Saved mesh variation mask as 'TrailerVariation 1'
2,034,433ms | Extended Asset Editor: 'TrailerVL80-tempfix23': Saved submesh variation mask as 'TrailerVariation 2'
2,034,433ms | Extended Asset Editor: 'TrailerVL80-tempfix23': Saved submesh variation mask as 'TrailerVariation 4'
2,034,433ms | Extended Asset Editor: 'TrailerVL80-tempfix23': Saved submesh variation mask as 'TrailerVariation 8'
2,034,433ms | Extended Asset Editor: 'TrailerVL80-tempfix23': Saved submesh variation mask as 'TrailerVariation 16'
2,034,433ms | Extended Asset Editor: 'TrailerVL80-tempfix23': Saved submesh variation mask as 'TrailerVariation 32'
2,034,433ms | Extended Asset Editor: 'TrailerVL80-tempfix23': Saved submesh variation mask as 'TrailerVariation 64'
2,034,433ms | Extended Asset Editor: 'TrailerVL80-tempfix23': Saved submesh variation mask as 'TrailerVariation 128'
2,034,433ms | Extended Asset Editor: 'TrailerVL80-tempfix23': Saved submesh variation mask as 'TrailerVariation 256'
```
Hm.. it work for me. I see all information of name in trailers
![image](https://user-images.githubusercontent.com/71866284/236957547-089eb0e2-dff1-4b76-92d1-87c86aafc8cc.png)

**Comment by Acc3ssViolation** [comment]
Good, I'm glad it's working
